# Generated by Django 4.2.7 on 2023-11-24 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('loan_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_lastname', models.CharField(max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
