# Generated by Django 4.2.7 on 2023-11-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
    ]
