# Generated by Django 4.2.7 on 2023-11-24 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autentificacion', '0002_remove_customuser_apellido_remove_customuser_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_cliente',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tarjeta_debito', models.PositiveSmallIntegerField()),
                ('retiros_realizados', models.PositiveSmallIntegerField()),
                ('chequera', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autentificacion.tipo_cliente')),
            ],
        ),
    ]
