# Generated by Django 4.2.7 on 2023-11-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autentificacion', '0004_alter_tipo_cliente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.PositiveIntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iban', models.TextField(max_length=150)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autentificacion.cliente')),
            ],
        ),
    ]
