# Generated by Django 4.2.7 on 2023-11-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_mov', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operacion', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nro_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.cuenta')),
            ],
        ),
    ]
