# Generated by Django 4.2.7 on 2023-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimientos', models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('compra', 'Compra')], max_length=20)),
            ],
        ),
    ]
