<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_mov', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operacion', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nro_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuentas.cuenta')),
            ],
        ),
    ]
=======
# Generated by Django 4.2.7 on 2023-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimientos', models.CharField(choices=[('ingreso', 'Ingreso'), ('transferencia', 'Transferencia'), ('compra', 'Compra')], max_length=20)),
            ],
        ),
    ]
>>>>>>> 7dbebc8187b3fbb31c7e7875adc67d63cfe2edc0
