# Generated by Django 4.2.7 on 2023-11-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=16)),
                ('titular', models.CharField(max_length=255)),
                ('fecha_expiracion', models.DateField()),
            ],
        ),
    ]
